/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/principal': typeof PrincipalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/principal': typeof PrincipalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/achievements': typeof AchievementsRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/principal': typeof PrincipalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/events'
    | '/facilities'
    | '/faculty'
    | '/gallery'
    | '/notices'
    | '/principal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/events'
    | '/facilities'
    | '/faculty'
    | '/gallery'
    | '/notices'
    | '/principal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/events'
    | '/facilities'
    | '/faculty'
    | '/gallery'
    | '/notices'
    | '/principal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AchievementsRoute: typeof AchievementsRoute
  EventsRoute: typeof EventsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  NoticesRoute: typeof NoticesRoute
  PrincipalRoute: typeof PrincipalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AchievementsRoute: AchievementsRoute,
  EventsRoute: EventsRoute,
  FacilitiesRoute: FacilitiesRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  NoticesRoute: NoticesRoute,
  PrincipalRoute: PrincipalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
